runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

libraries:
- name: ssl
  version: 2.7

handlers:
- url: /static
  static_dir: static
  secure: always
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin
  secure: always
- url: /.*
  script: main.app
  secure: always


