runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

handlers:
- url: /static
  static_dir: static
# - url: /(.*\.(js|gif|png|jpg|ico|bmp|css|otf|eot|svg|ttf|woff))$
#   static_files: static/\1
#   upload: static/.*\.(js|gif|png|jpg|ico|bmp|css|otf|eot|svg|ttf|woff)$
- url: /.*
  script: main.app
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

